#!/bin/sh

CONFIG="/etc/pump.io.json"

# Default values
PUMPIO_DRIVER=${PUMPIO_DRIVER:="mongodb"}
PUMPIO_DBNAME=${PUMPIO_DBNAME:="pumpiodb"}
PUMPIO_DBIP=${PUMPIO_DBIP:="172.17.0.1"}
PUMPIO_DBPORT=${PUMPIO_DBPORT:="27017"}
PUMPIO_HOSTNAME=${PUMPIO_HOSTNAME:="pumpio.example.com"}
PUMPIO_ADDRESS=${PUMPIO_ADDRESS:="0.0.0.0"}
PUMPIO_PORT=${PUMPIO_PORT:="443"}
PUMPIO_URLPORT=${PUMPIO_URLPORT:="443"}
PUMPIO_SECRET=${PUMPIO_SECRET:="123456789_ISBADONE_CHANGEME"}
PUMPIO_NOWEB=${PUMPIO_NOWEB:="false"}
PUMPIO_SITE=${PUMPIO_SITE:="My pump.io site using Docker"}
PUMPIO_OWNER=${PUMPIO_OWNER:="My name is Docker"}
PUMPIO_OWNERURL=${PUMPIO_OWNERURL:="http:\/\/dockerio.cloudapp.net"}
PUMPIO_NOLOGGER=${PUMPIO_NOLOGGER:="false"}
PUMPIO_LOGFILE=${PUMPIO_LOGFILE:="\/dev\/null"}
PUMPIO_SERVERUSER=${PUMPIO_SERVERUSER:="pumpio"}
PUMPIO_KEY=${PUMPIO_KEY:="\/etc\/ssl\/private\/privkey.pem"}
PUMPIO_CERT=${PUMPIO_CERT:="\/etc\/ssl\/private\/fullchain.pem"}
PUMPIO_HSTS=${PUMPIO_HSTS:="false"}
PUMPIO_DATADIR=${PUMPIO_DATADIR:="\/data"}
PUMPIO_ENABLEUPLOADS=${PUMPIO_ENABLEUPLOADS:="true"}
PUMPIO_DEBUGCLIENT=${PUMPIO_DEBUGCLIENT:="false"}
PUMPIO_FIREHOSE=${PUMPIO_FIREHOSE:="ofirehose.com"}
PUMPIO_SPAMHOST=${PUMPIO_SPAMHOST:="null"}
PUMPIO_SPAMCLIENTID=${PUMPIO_SPAMCLIENTID:="null"}
PUMPIO_SPAMCLIENTSECRET=${PUMPIO_SPAMCLIENTSECRET:="null"}
PUMPIO_DISABLEREGISTRATION=${PUMPIO_DISABLEREGISTRATION:="false"}
PUMPIO_NOCDN=${PUMPIO_NOCDN:="false"}
PUMPIO_REQUIREEMAIL=${PUMPIO_REQUIREEMAIL:="false"}
PUMPIO_SMTPSERVER=${PUMPIO_SMTPSERVER:="null"}
PUMPIO_SMTPPORT=${PUMPIO_SMTPPORT:="25"}
PUMPIO_SMTPUSER=${PUMPIO_SMTPUSER:="null"}
PUMPIO_SMTPPASS=${PUMPIO_SMTPPASS:="null"}
PUMPIO_SMTPUSETLS=${PUMPIO_SMTPUSETLS:="true"}
PUMPIO_SMTPUSESSL=${PUMPIO_SMTPUSESSL:="false"}
PUMPIO_SMTPTIMEOUT=${PUMPIO_SMTPTIMEOUT:="null"}
PUMPIO_SMTPFROM=${PUMPIO_SMTPFROM:="null"}
PUMPIO_COMPRESS=${PUMPIO_COMPRESS:="true"}
PUMPIO_CHILDREN=${PUMPIO_CHILDREN:="1"}
PUMPIO_CLIENTS=${PUMPIO_CLIENTS:="1"}
PUMPIO_SOCKJS=${PUMPIO_SOCKJS:="true"}
PUMPIO_CLEANUPSESSION=${PUMPIO_CLEANUPSESSION:="1200000"}
PUMPIO_CLEANUPNONCE=${PUMPIO_CLEANUPNONCE:="1200000"}
PUMPIO_FAVICON=${PUMPIO_FAVICON:="\/usr\/lib\/node_modules\/pump.io\/public\/images\/favicon.ico"}

# Put them in config
sed -i "s/PUMPIO_DRIVER/$PUMPIO_DRIVER/" $CONFIG
sed -i "s/PUMPIO_DBNAME/$PUMPIO_DBNAME/" $CONFIG
sed -i "s/PUMPIO_DBIP/$PUMPIO_DBIP/" $CONFIG
sed -i "s/PUMPIO_DBPORT/$PUMPIO_DBPORT/" $CONFIG
sed -i "s/PUMPIO_HOSTNAME/$PUMPIO_HOSTNAME/" $CONFIG
sed -i "s/PUMPIO_ADDRESS/$PUMPIO_ADDRESS/" $CONFIG
sed -i "s/PUMPIO_PORT/$PUMPIO_PORT/" $CONFIG
sed -i "s/PUMPIO_URLPORT/$PUMPIO_URLPORT/" $CONFIG
sed -i "s/PUMPIO_SECRET/$PUMPIO_SECRET/" $CONFIG
sed -i "s/PUMPIO_NOWEB/$PUMPIO_NOWEB/" $CONFIG
sed -i "s/PUMPIO_SITE/$PUMPIO_SITE/" $CONFIG
sed -i "s/PUMPIO_OWNER/$PUMPIO_OWNER/" $CONFIG
sed -i "s/PUMPIO_OWNERURL/$PUMPIO_OWNERURL/" $CONFIG
sed -i "s/PUMPIO_NOLOGGER/$PUMPIO_NOLOGGER/" $CONFIG
sed -i "s/PUMPIO_LOGFILE/$PUMPIO_LOGFILE/" $CONFIG
sed -i "s/PUMPIO_SERVERUSER/$PUMPIO_SERVERUSER/" $CONFIG
sed -i "s/PUMPIO_KEY/$PUMPIO_KEY/" $CONFIG
sed -i "s/PUMPIO_CERT/$PUMPIO_CERT/" $CONFIG
sed -i "s/PUMPIO_HSTS/$PUMPIO_HSTS/" $CONFIG
sed -i "s/PUMPIO_DATADIR/$PUMPIO_DATADIR/" $CONFIG
sed -i "s/PUMPIO_ENABLEUPLOADS/$PUMPIO_ENABLEUPLOADS/" $CONFIG
sed -i "s/PUMPIO_DEBUGCLIENT/$PUMPIO_DEBUGCLIENT/" $CONFIG
sed -i "s/PUMPIO_FIREHOSE/$PUMPIO_FIREHOSE/" $CONFIG
sed -i "s/PUMPIO_SPAMHOST/$PUMPIO_SPAMHOST/" $CONFIG
sed -i "s/PUMPIO_SPAMCLIENTID/$PUMPIO_SPAMCLIENTID/" $CONFIG
sed -i "s/PUMPIO_SPAMCLIENTSECRET/$PUMPIO_SPAMCLIENTSECRET/" $CONFIG
sed -i "s/PUMPIO_DISABLEREGISTRATION/$PUMPIO_DISABLEREGISTRATION/" $CONFIG
sed -i "s/PUMPIO_NOCDN/$PUMPIO_NOCDN/" $CONFIG
sed -i "s/PUMPIO_REQUIREEMAIL/$PUMPIO_REQUIREEMAIL/" $CONFIG
sed -i "s/PUMPIO_SMTPSERVER/$PUMPIO_SMTPSERVER/" $CONFIG
sed -i "s/PUMPIO_SMTPPORT/$PUMPIO_SMTPPORT/" $CONFIG
sed -i "s/PUMPIO_SMTPUSER/$PUMPIO_SMTPUSER/" $CONFIG
sed -i "s/PUMPIO_SMTPPASS/$PUMPIO_SMTPPASS/" $CONFIG
sed -i "s/PUMPIO_SMTPUSETLS/$PUMPIO_SMTPUSETLS/" $CONFIG
sed -i "s/PUMPIO_SMTPUSESSL/$PUMPIO_SMTPUSESSL/" $CONFIG
sed -i "s/PUMPIO_SMTPTIMEOUT/$PUMPIO_SMTPTIMEOUT/" $CONFIG
sed -i "s/PUMPIO_SMTPFROM/$PUMPIO_SMTPFROM/" $CONFIG
sed -i "s/PUMPIO_COMPRESS/$PUMPIO_COMPRESS/" $CONFIG
sed -i "s/PUMPIO_CHILDREN/$PUMPIO_CHILDREN/" $CONFIG
sed -i "s/PUMPIO_CLIENTS/$PUMPIO_CLIENTS/" $CONFIG
sed -i "s/PUMPIO_SOCKJS/$PUMPIO_SOCKJS/" $CONFIG
sed -i "s/PUMPIO_CLEANUPSESSION/$PUMPIO_CLEANUPSESSION/" $CONFIG
sed -i "s/PUMPIO_CLEANUPNONCE/$PUMPIO_CLEANUPNONCE/" $CONFIG
sed -i "s/PUMPIO_FAVICON/$PUMPIO_FAVICON/" $CONFIG

/usr/bin/pump
