// user.js
//
// A local user; distinct from a person
//
// Copyright 2011,2012 StatusNet Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

var databank = require('databank'),
    _ = require('underscore'),
    DatabankObject = databank.DatabankObject,
    dateFormat = require('dateformat'),
    bcrypt  = require('bcrypt'),
    Step = require('step'),
    Person = require('./person').Person,
    Stream = require('./stream').Stream,
    ActivityObject = require('./activityobject').ActivityObject,
    URLMaker = require('../urlmaker').URLMaker,
    NoSuchThingError = databank.NoSuchThingError;

var User = DatabankObject.subClass('user');

exports.User = User;

// for updating

User.prototype.beforeUpdate = function(props, callback) {

    // XXX: required, but immutable. Boooooo.

    if (!_(props).has('nickname')) {
        callback(new Error("'nickname' property is required"), null);
        return;
    } else if (props.nickname !== this.nickname) {
        callback(new Error("'nickname' is immutable"), null);
        return;
    } else {
        delete props.nickname;
    }

    // XXX: required. Seems not strictly necessary, but whatever.

    if (!_(props).has('password')) {
        callback(new Error("'password' property is required"), null);
        return;
    }

    props.passwordHash = bcrypt.hashSync(props.password, bcrypt.genSaltSync(10));
    delete props.password;

    // Callers must omit or leave equal

    if (_(props).has('published')) {
        if (props.published !== this.published) {
            callback(new Error("'published' is autogenerated and immutable"), null);
            return;
        } else {
            delete props.published;
        }
    }

    // Callers must omit or leave equal

    if (_(props).has('profile')) {
        // XXX: we should probably do some deep-equality check
        if (!_(props.profile).has('id') || props.profile.id !== this.profile.id ||
            !_(props.profile).has('objectType') || props.profile.objectType !== this.profile.objectType ||
            !_(props.profile).has('displayName') || props.profile.displayName !== this.profile.displayName) {
            callback(new Error("'profile' is immutable"), null);
            return;
        } else {
            delete props.profile;
        }
    }

    // Callers must omit or leave equal

    if (_(props).has('updated') && props.updated !== this.updated) {
        callback(new Error("'updated' is autogenerated"), null);
        return;
    }

    props.updated = dateFormat(new Date(), "isoDateTime", true);

    callback(null, props);
};

// For creating

User.beforeCreate = function(props, callback) {

    if (!props.nickname || !props.password) {
        callback(new Error('Gotta have a nickname and a password.'), null);
        return;
    }

    props.passwordHash  = bcrypt.hashSync(props.password, bcrypt.genSaltSync(10));

    delete props.password;

    var now = dateFormat(new Date(), "isoDateTime", true);

    props.published = props.updated = now;

    Step(
        function() {
            Person.create({'preferredUsername': props.nickname,
                           url: URLMaker.makeURL(props.nickname),
                           displayName: props.nickname}, this);
        },
        function(err, person) {
            if (err) throw err;
            props.profile = {
                objectType: 'person',
                id: person.id
            };

            Stream.create({name: props.nickname + "-inbox"}, this.parallel());
            Stream.create({name: props.nickname + "-outbox"}, this.parallel());
        },
        function(err, inbox, outbox) {
            callback(null, props);
        }
    );
};

User.prototype.sanitize = function() {
    delete this.password;
    delete this.passwordHash;
};

User.prototype.getProfile = function(callback) {
    var user = this;
    Step(
        function() {
            ActivityObject.getObject(user.profile.objectType, user.profile.id, this);
        },
        function(err, profile) {
            if (err) {
                callback(err, null);
            } else {
                callback(null, profile);
            }
        }
    );
};

User.prototype.getStream = function(start, end, callback) {
    var bank = User.bank(),
        user = this; 

    Step(
        function() {
            Stream.get(user.nickname + '-outbox', this);
        },
        function(err, outbox) {
            if (err) throw err;
            outbox.getActivities(start, end, this);
        },
        function(err, activities) {
            var group = this.group();
            if (err) throw err;
            // FIXME: batch fetch all actors and objects
            activities.forEach(function(el, i, arr) {
                delete el.uuid;
                delete el.actor;
                el.expandObject(group());
                // remove internal uuid info, if any
            });
        },
        function(err, activities) {
            if (err) {
                if (err instanceof NoSuchThingError) {
                    callback(null, []);
                } else {
                    callback(err, null);
                }
            } else {
                callback(null, activities);
            }
        }
    );
};

User.prototype.getInbox = function(start, end, callback) {
    var bank = User.bank(),
        user = this; 

    Step(
        function() {
            Stream.get(user.nickname + '-inbox', this);
        },
        function(err, inbox) {
            if (err) throw err;
            inbox.getActivities(start, end, this);
        },
        function(err, activities) {
            var group = this.group();
            if (err) throw err;
            // FIXME: batch fetch all actors and objects
            activities.forEach(function(el, i, arr) {
                delete el.uuid;
                el.expand(group());
                // remove internal uuid info, if any
            });
        },
        function(err, activities) {
            if (err) {
                if (err instanceof NoSuchThingError) {
                    callback(null, []);
                } else {
                    callback(err, null);
                }
            } else {
                callback(null, activities);
            }
        }
    );
};

User.prototype.expand = function(callback) {
    var user = this;

    Step(
        function() {
            user.getProfile(this);
        },
        function(err, profile) {
            if (err) {
                callback(err, null);
            } else {
                _.extend(user.profile, profile);
                callback(null, user);
            }
        }
    );
};

User.fromPerson = function(id, callback) {
    Step(
        function() {
            User.search({"profile.id": id}, this);
        },
        function(err, results) {
            if (err) {
                callback(err, null);
            } else if (results.length === 0) {
                callback(null, null);
            } else {
                callback(null, results[0]);
            }
        }
    );
};

User.prototype.addToOutbox = function(activity, callback) {
    var user = this;
    Step(
        function() {
            Stream.get(user.nickname + "-outbox", this);
        },
        function(err, stream) {
            if (err) throw err;
            stream.deliver(activity, callback);
        }
    );
};

User.prototype.addToInbox = function(activity, callback) {
    var user = this;
    Step(
        function() {
            Stream.get(user.nickname + "-inbox", this);
        },
        function(err, stream) {
            if (err) throw err;
            stream.deliver(activity, callback);
        }
    );
};

// Check the credentials for a user
// callback takes args:
// - err: if there's an error (NB: null if credentials don't match)
// - user: User object or null if credentials don't match

User.checkCredentials = function(nickname, password, callback) {
    var user = null;

    Step(
        function() {
            User.get(nickname, this);
        },
        function(err, result) {
            if (err) {
                if (err instanceof NoSuchThingError) {
                    callback(null, null);
                    return; // done
                } else {
                    throw err;
                }
            } else {
                user = result;
                bcrypt.compare(password, user.passwordHash, this);
            }
        },
        function(err, res) {
            if (err) {
                callback(err, null);
            } else if (!res) {
                callback(null, null);
            } else {
                // Don't percolate that hash around
                user.sanitize();
                callback(null, user);
            }
        }
    );
};

User.schema = {'pkey': 'nickname',
               'fields': ['passwordHash',
                          'published',
                          'updated',
                          'profile'],
               'indices': ['profile.id']};
